# -*- coding: utf-8 -*-
"""MAYUR MAJOR PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqOHTpmG_RWxwXNBaebqZ1wAskXjV6GE

MAJOR PROJECT : TAKING A DATASET, PERFORMING EDA, APPLYING SUITABLE CLASSIFIER/REGRESSOR/CLUSTERER AND CALCULATING ACCURACY OF MODEL.
"""

#1. TAKE DATASET AND CREATE DATAFRAME
#DATASET - "https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/CarPrice_Assignment.csv"
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/CarPrice_Assignment.csv")
df

#2. MEASURING DATAFRAME
df.shape

df.size

df.info

df.CarName.unique()

#3. VISUALISING THE DATA
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
plt.figure(figsize=(16,6))

plt.subplot(1,2,1)
plt.title('Car Price Distribution Plot')
sns.distplot(df.price)

plt.subplot(1,2,2)
plt.title('Car Price Spread')
sns.boxplot(y=df.price)

plt.show()

df = pd.DataFrame(df.groupby(['enginetype'])['price'].mean().sort_values(ascending = False))
df.plot.bar(figsize=(8,6))
plt.title('Engine Type vs Average Price')
plt.show()

#4. DIVIDING DATA (SICING)
X=df.iloc[:,0:5]
X

df.iloc[:,0:5].values

y=df.iloc[:,0:7]
y

#5. TRAIN AND TEST VARIABLES
from sklearn.model_selection import train_test_split
import numpy as np

np.random.seed(0)
df_train, df_test = train_test_split(df, train_size = 0.7, test_size = 0.3, random_state = 100)

#6. APPLYING A CLASSIFIER/REGRESSOR/CLUSTERER
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model

#7. FIT THE MODEL
model.fit(x,y)

#8. PREDICT THE MODEL OUTPUT
y_pred = model.predict(x)
y_pred

y